-- ---------- Foundations (5) ----------
insert into foundations (name, description, website, contact_email, contact_phone) values
('Cedar Valley Community Foundation', 'Regional foundation funding neighborhood, small-business, and emergency-relief projects across the Cedar Valley area.', 'https://cedarvalleycf.org',   'grants@cedarvalleycf.org',   '555-0142'),
('The Hartwell Arts Trust',           'Endowed trust supporting individual artists and arts organizations through fellowships, commissions, and operating grants.', 'https://hartwellarts.org',    'apply@hartwellarts.org',     '555-0198'),
('Meridian Health Foundation',        'Health-focused funder backing community clinics, health innovation, and healthcare workforce scholarships.', 'https://meridianhealthfdn.org','info@meridianhealthfdn.org', '555-0173'),
('GreenFuture Environmental Fund',    'Environmental grantmaker funding urban greening, watershed restoration, and sustainable agriculture.', 'https://greenfuturefund.org', 'grants@greenfuturefund.org', '555-0121'),
('TechForward Education Initiative',  'Education funder advancing STEM access, EdTech pilots, and scholarships for first-generation students.', 'https://techforward.org',     'hello@techforward.org',      '555-0160');

-- ---------- Grants (19: mixed status & eligibility) ----------
insert into grants (foundation_id, title, description, award_min, award_max, eligibility, application_deadline, status, source) values
((select id from foundations where name='Cedar Valley Community Foundation'), 'Neighborhood Small Grants Program',       'Micro-grants for grassroots neighborhood improvement projects.',                 500,     5000,   'both',         current_date + 45, 'open',    'manual'),
((select id from foundations where name='Cedar Valley Community Foundation'), 'Local Entrepreneur Microgrant',           'Startup capital for individual local entrepreneurs.',                            1000,    10000,  'individual',   current_date + 90, 'open',    'manual'),
((select id from foundations where name='Cedar Valley Community Foundation'), 'Community Facilities Improvement Fund',   'Capital improvements for community centers and shared facilities.',              10000,   75000,  'organization', current_date - 20, 'closed',  'manual'),
((select id from foundations where name='Cedar Valley Community Foundation'), 'Emergency Relief Fund',                   'Rapid-response relief for individuals and small orgs facing crises.',            250,     2500,   'both',         null,              'rolling', 'manual'),
((select id from foundations where name='The Hartwell Arts Trust'),           'Emerging Artist Fellowship',              'Unrestricted fellowship for early-career individual artists.',                   5000,    25000,  'individual',   current_date + 60, 'open',    'manual'),
((select id from foundations where name='The Hartwell Arts Trust'),           'Arts Organization Operating Grant',       'General operating support for established arts nonprofits.',                     20000,   150000, 'organization', current_date - 10, 'closed',  'manual'),
((select id from foundations where name='The Hartwell Arts Trust'),           'Public Mural Commission',                 'Commissions for public murals by individual artists or collectives.',            3000,    15000,  'both',         current_date + 30, 'open',    'manual'),
((select id from foundations where name='The Hartwell Arts Trust'),           'Performing Arts Touring Grant',           'Travel and production support for touring performing-arts organizations.',       8000,    40000,  'organization', null,              'rolling', 'manual'),
((select id from foundations where name='Meridian Health Foundation'),        'Community Health Innovation Award',       'Funds novel community-health delivery models.',                                  25000,   200000, 'organization', current_date + 75, 'open',    'manual'),
((select id from foundations where name='Meridian Health Foundation'),        'Nursing Scholarship Fund',                'Tuition support for individuals pursuing nursing credentials.',                  2000,    12000,  'individual',   current_date + 120,'open',    'manual'),
((select id from foundations where name='Meridian Health Foundation'),        'Rural Clinic Equipment Grant',            'Medical equipment funding for rural clinics.',                                   15000,   100000, 'organization', current_date - 30, 'closed',  'manual'),
((select id from foundations where name='Meridian Health Foundation'),        'Mental Health Access Grant',              'Expands mental-health services for underserved populations.',                    10000,   60000,  'both',         current_date + 50, 'open',    'manual'),
((select id from foundations where name='GreenFuture Environmental Fund'),    'Urban Greening Grant',                    'Tree-planting, pocket parks, and green infrastructure projects.',                5000,    50000,  'organization', current_date + 40, 'open',    'manual'),
((select id from foundations where name='GreenFuture Environmental Fund'),    'Youth Climate Action Grant',              'Seed funding for youth-led climate projects.',                                   1000,    8000,   'individual',   current_date + 25, 'open',    'manual'),
((select id from foundations where name='GreenFuture Environmental Fund'),    'Watershed Restoration Fund',              'Large-scale watershed and wetland restoration.',                                 30000,   250000, 'organization', current_date - 45, 'closed',  'manual'),
((select id from foundations where name='GreenFuture Environmental Fund'),    'Sustainable Farming Transition Grant',    'Supports farms transitioning to sustainable practices.',                         10000,   80000,  'both',         null,              'rolling', 'manual'),
((select id from foundations where name='TechForward Education Initiative'),  'STEM Classroom Grant',                    'Equipment and curriculum funding for K-12 STEM classrooms.',                     2000,    20000,  'organization', current_date + 35, 'open',    'manual'),
((select id from foundations where name='TechForward Education Initiative'),  'First-Gen Coding Scholarship',            'Bootcamp/degree scholarships for first-generation coding students.',             3000,    15000,  'individual',   current_date + 100,'open',    'manual'),
((select id from foundations where name='TechForward Education Initiative'),  'EdTech Pilot Grant',                      'Pilot funding for classroom EdTech tools.',                                      25000,   120000, 'organization', current_date - 15, 'closed',  'manual');

-- ---------- Past awards (26) ----------
insert into past_awards (grant_id, winner_name, winner_type, award_date, award_amount, notes) values
((select id from grants where title='Community Facilities Improvement Fund'), 'Riverside Community Center',        'organization', current_date - 400, 62000,  'Renovated an aging gymnasium into a multi-use youth space; strong volunteer match.'),
((select id from grants where title='Community Facilities Improvement Fund'), 'Eastside Neighborhood Alliance',    'organization', current_date - 760, 45000,  'Accessibility upgrades to a shared community kitchen.'),
((select id from grants where title='Arts Organization Operating Grant'),     'Cedar Valley Repertory Theatre',    'organization', current_date - 380, 120000, 'Sustained programming through a difficult season; clear audience-growth metrics.'),
((select id from grants where title='Arts Organization Operating Grant'),     'Hartwell Chamber Orchestra',        'organization', current_date - 740, 95000,  'Expanded free community concert series.'),
((select id from grants where title='Emerging Artist Fellowship'),            'Maya Okonkwo',                      'individual',   current_date - 200, 20000,  'Mixed-media series on regional migration; exceptional portfolio.'),
((select id from grants where title='Emerging Artist Fellowship'),            'Daniel Reyes',                      'individual',   current_date - 560, 18000,  'Documentary photography of vanishing farm towns.'),
((select id from grants where title='Emerging Artist Fellowship'),            'Priya Nair',                        'individual',   current_date - 920, 22000,  'Sculptural installation using reclaimed materials.'),
((select id from grants where title='Public Mural Commission'),               'The Collective Brush',              'organization', current_date - 150, 12000,  'Community-designed mural on the transit hub wall.'),
((select id from grants where title='Public Mural Commission'),               'Tomas Vela',                        'individual',   current_date - 500, 9000,   'Solo mural celebrating local Indigenous history.'),
((select id from grants where title='Performing Arts Touring Grant'),         'Northern Lights Dance Company',     'organization', current_date - 120, 32000,  'Six-city regional tour with education workshops.'),
((select id from grants where title='Rural Clinic Equipment Grant'),          'Prairie Health Cooperative',        'organization', current_date - 300, 88000,  'Purchased portable diagnostic equipment for mobile clinics.'),
((select id from grants where title='Rural Clinic Equipment Grant'),          'Valley Ridge Community Clinic',     'organization', current_date - 680, 72000,  'Upgraded lab and imaging capacity serving 4 rural counties.'),
((select id from grants where title='Community Health Innovation Award'),     'OpenCare Telehealth Initiative',    'organization', current_date - 250, 175000, 'Telehealth model reduced no-show rates by 40%.'),
((select id from grants where title='Nursing Scholarship Fund'),              'Aaliyah Bennett',                   'individual',   current_date - 180, 10000,  'Second-career RN candidate; strong community-service record.'),
((select id from grants where title='Nursing Scholarship Fund'),              'Marcus Trent',                      'individual',   current_date - 540, 11000,  'Rural nursing commitment after graduation.'),
((select id from grants where title='Mental Health Access Grant'),            'Bridges Counseling Network',        'organization', current_date - 220, 55000,  'Sliding-scale therapy expansion in underserved zip codes.'),
((select id from grants where title='Urban Greening Grant'),                  'City Roots Coalition',              'organization', current_date - 160, 44000,  '14 pocket parks and 300 street trees in heat-island zones.'),
((select id from grants where title='Watershed Restoration Fund'),            'Clearwater Restoration Trust',      'organization', current_date - 350, 220000, 'Restored 3 miles of degraded streambank; measurable water-quality gains.'),
((select id from grants where title='Watershed Restoration Fund'),            'Meadowbrook Conservancy',           'organization', current_date - 700, 190000, 'Wetland reconstruction restored native waterfowl habitat.'),
((select id from grants where title='Youth Climate Action Grant'),            'Sofia Alvarez',                     'individual',   current_date - 140, 7000,   'Student-led school solar-education program.'),
((select id from grants where title='Youth Climate Action Grant'),            'Jordan Kim',                        'individual',   current_date - 480, 6500,   'Neighborhood composting network founded by a high-schooler.'),
((select id from grants where title='Sustainable Farming Transition Grant'),  'Hollow Creek Farm',                 'organization', current_date - 130, 60000,  'Transitioned 80 acres to no-till regenerative practices.'),
((select id from grants where title='EdTech Pilot Grant'),                    'Lincoln Unified School District',   'organization', current_date - 210, 95000,  'Adaptive-math pilot across 12 classrooms; gains in proficiency scores.'),
((select id from grants where title='STEM Classroom Grant'),                  'Westbrook Middle School',           'organization', current_date - 190, 16000,  'Robotics lab serving 200 students.'),
((select id from grants where title='First-Gen Coding Scholarship'),          'Elena Vasquez',                     'individual',   current_date - 170, 12000,  'First-gen student; completed full-stack bootcamp, now employed.'),
((select id from grants where title='Local Entrepreneur Microgrant'),         'Corner Cup Coffee',                 'organization', current_date - 260, 8000,   'Micro-roastery expansion; created 3 local jobs.');
