-- Seed data intentionally left empty.
--
-- The catalog (foundations / programs / grants / awards / disclosures) is now
-- populated from real Canadian data by the ingestion pipeline (section 5), not
-- from mock rows:
--   bun run ingest --source=canadian-heritage
--   bun run ingest --source=canada-council
--
-- `supabase db reset` rebuilds the schema and runs this file; run the ingestion
-- afterwards to load data. The previous fictional seed is preserved in git
-- history (see the initial commit) if you need it for reference.
