ALTER TABLE public.foundations ADD COLUMN source text;
ALTER TABLE public.foundations ADD COLUMN source_external_id text;
ALTER TABLE public.foundations ADD COLUMN last_seen_at timestamp with time zone;
ALTER TABLE public.past_awards ADD COLUMN source text;
ALTER TABLE public.past_awards ADD COLUMN source_external_id text;
ALTER TABLE public.past_awards ADD CONSTRAINT past_awards_source_source_external_id_key UNIQUE (source, source_external_id);
ALTER TABLE public.past_awards ADD COLUMN last_seen_at timestamp with time zone;
CREATE TABLE public.raw_ingest (id uuid DEFAULT gen_random_uuid() NOT NULL, source text NOT NULL, source_external_id text NOT NULL, payload jsonb NOT NULL, sync_run_id uuid, fetched_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.raw_ingest ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.raw_ingest ADD CONSTRAINT raw_ingest_pkey PRIMARY KEY (id);
ALTER TABLE public.raw_ingest ADD CONSTRAINT raw_ingest_source_source_external_id_key UNIQUE (source, source_external_id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.raw_ingest TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.raw_ingest TO authenticated;
GRANT ALL ON public.raw_ingest TO service_role;
CREATE INDEX raw_ingest_source_idx ON public.raw_ingest (source);
CREATE TABLE public.sync_runs (id uuid DEFAULT gen_random_uuid() NOT NULL, source text NOT NULL, started_at timestamp with time zone DEFAULT now() NOT NULL, finished_at timestamp with time zone, status text DEFAULT 'running'::text NOT NULL, items_fetched integer DEFAULT 0 NOT NULL, items_upserted integer DEFAULT 0 NOT NULL, error_text text);
ALTER TABLE public.sync_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_runs ADD CONSTRAINT sync_runs_pkey PRIMARY KEY (id);
ALTER TABLE public.raw_ingest ADD CONSTRAINT raw_ingest_sync_run_id_fkey FOREIGN KEY (sync_run_id) REFERENCES public.sync_runs(id) ON DELETE SET NULL;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.sync_runs TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.sync_runs TO authenticated;
GRANT ALL ON public.sync_runs TO service_role;
CREATE INDEX sync_runs_source_idx ON public.sync_runs (source, started_at DESC);
