SET check_function_bodies = false;
CREATE TYPE public.applicant_type AS ENUM ('individual', 'organization');
CREATE TYPE public.application_status AS ENUM ('draft', 'submitted', 'under_review', 'awarded', 'rejected', 'withdrawn');
CREATE TYPE public.eligibility_type AS ENUM ('individual', 'organization', 'both');
CREATE TYPE public.grant_status AS ENUM ('open', 'closed', 'rolling');
CREATE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin new.updated_at = now(); return new; end;
$function$;
CREATE TABLE public.applicants (id uuid DEFAULT gen_random_uuid() NOT NULL, owner_id uuid NOT NULL, type public.applicant_type NOT NULL, display_name text NOT NULL, is_self boolean DEFAULT false NOT NULL, email text, phone text, bio text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.applicants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applicants ADD CONSTRAINT applicants_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.applicants ADD CONSTRAINT applicants_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.applicants TO anon;
GRANT ALL ON public.applicants TO authenticated;
GRANT ALL ON public.applicants TO service_role;
CREATE INDEX applicants_owner_idx ON public.applicants (owner_id);
CREATE TRIGGER t_applicants_upd BEFORE UPDATE ON public.applicants FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY own_applicants ON public.applicants USING ((auth.uid() = owner_id)) WITH CHECK ((auth.uid() = owner_id));
CREATE TABLE public.applications (id uuid DEFAULT gen_random_uuid() NOT NULL, owner_id uuid NOT NULL, applicant_id uuid NOT NULL, grant_id uuid NOT NULL, status public.application_status DEFAULT 'draft'::public.application_status NOT NULL, submitted_at timestamp with time zone, notes text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ADD CONSTRAINT applications_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES public.applicants(id) ON DELETE CASCADE;
ALTER TABLE public.applications ADD CONSTRAINT applications_applicant_id_grant_id_key UNIQUE (applicant_id, grant_id);
ALTER TABLE public.applications ADD CONSTRAINT applications_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.applications ADD CONSTRAINT applications_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.applications TO anon;
GRANT ALL ON public.applications TO authenticated;
GRANT ALL ON public.applications TO service_role;
CREATE INDEX applications_grant_idx ON public.applications (grant_id);
CREATE INDEX applications_owner_idx ON public.applications (owner_id);
CREATE TRIGGER t_applications_upd BEFORE UPDATE ON public.applications FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY own_applications ON public.applications USING ((auth.uid() = owner_id)) WITH CHECK ((auth.uid() = owner_id));
CREATE TABLE public.foundations (id uuid DEFAULT gen_random_uuid() NOT NULL, name text NOT NULL, description text, website text, contact_email text, contact_phone text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.foundations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.foundations ADD CONSTRAINT foundations_name_key UNIQUE (name);
ALTER TABLE public.foundations ADD CONSTRAINT foundations_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.foundations TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.foundations TO authenticated;
GRANT ALL ON public.foundations TO service_role;
CREATE TRIGGER t_foundations_upd BEFORE UPDATE ON public.foundations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY catalog_read_foundations ON public.foundations FOR SELECT USING (true);
CREATE TABLE public.grants (id uuid DEFAULT gen_random_uuid() NOT NULL, foundation_id uuid NOT NULL, title text NOT NULL, description text, award_min numeric(12,2), award_max numeric(12,2), eligibility public.eligibility_type DEFAULT 'both'::public.eligibility_type NOT NULL, application_deadline date, status public.grant_status DEFAULT 'open'::public.grant_status NOT NULL, source text, source_external_id text, last_seen_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grants ADD CONSTRAINT amount_range_valid CHECK (award_max IS NULL OR award_min IS NULL OR award_max >= award_min);
ALTER TABLE public.grants ADD CONSTRAINT grants_foundation_id_fkey FOREIGN KEY (foundation_id) REFERENCES public.foundations(id) ON DELETE CASCADE;
ALTER TABLE public.grants ADD CONSTRAINT grants_pkey PRIMARY KEY (id);
ALTER TABLE public.applications ADD CONSTRAINT applications_grant_id_fkey FOREIGN KEY (grant_id) REFERENCES public.grants(id) ON DELETE CASCADE;
ALTER TABLE public.grants ADD CONSTRAINT grants_source_source_external_id_key UNIQUE (source, source_external_id);
ALTER TABLE public.grants ADD CONSTRAINT grants_title_key UNIQUE (title);
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.grants TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.grants TO authenticated;
GRANT ALL ON public.grants TO service_role;
CREATE INDEX grants_foundation_idx ON public.grants (foundation_id);
CREATE INDEX grants_status_idx ON public.grants (status);
CREATE INDEX grants_deadline_idx ON public.grants (application_deadline);
CREATE INDEX grants_eligibility_idx ON public.grants (eligibility);
CREATE TRIGGER t_grants_upd BEFORE UPDATE ON public.grants FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE POLICY catalog_read_grants ON public.grants FOR SELECT USING (true);
CREATE TABLE public.past_awards (id uuid DEFAULT gen_random_uuid() NOT NULL, grant_id uuid NOT NULL, winner_name text NOT NULL, winner_type public.applicant_type NOT NULL, award_date date, award_amount numeric(12,2), notes text, created_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.past_awards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.past_awards ADD CONSTRAINT past_awards_grant_id_fkey FOREIGN KEY (grant_id) REFERENCES public.grants(id) ON DELETE CASCADE;
ALTER TABLE public.past_awards ADD CONSTRAINT past_awards_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.past_awards TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.past_awards TO authenticated;
GRANT ALL ON public.past_awards TO service_role;
CREATE INDEX past_awards_grant_idx ON public.past_awards (grant_id);
CREATE POLICY catalog_read_awards ON public.past_awards FOR SELECT USING (true);
CREATE TABLE public.saved_grants (id uuid DEFAULT gen_random_uuid() NOT NULL, owner_id uuid NOT NULL, grant_id uuid NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.saved_grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_grants ADD CONSTRAINT saved_grants_grant_id_fkey FOREIGN KEY (grant_id) REFERENCES public.grants(id) ON DELETE CASCADE;
ALTER TABLE public.saved_grants ADD CONSTRAINT saved_grants_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.saved_grants ADD CONSTRAINT saved_grants_owner_id_grant_id_key UNIQUE (owner_id, grant_id);
ALTER TABLE public.saved_grants ADD CONSTRAINT saved_grants_pkey PRIMARY KEY (id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.saved_grants TO anon;
GRANT ALL ON public.saved_grants TO authenticated;
GRANT ALL ON public.saved_grants TO service_role;
CREATE INDEX saved_grants_owner_idx ON public.saved_grants (owner_id);
CREATE POLICY own_saved ON public.saved_grants USING ((auth.uid() = owner_id)) WITH CHECK ((auth.uid() = owner_id));
